project_id = "hzehxkoyotdedhcqkrug"

[functions.stock-data]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.ai-stock-summary]
verify_jwt = false

[functions.news-sentiment]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.stock-chat]
verify_jwt = false